export const UNIQUE_SEGMENT_LENGTH = 9;
export const UNIQUE_SEGMENT_COUNT = UNIQUE_SEGMENT_LENGTH;
export const SUBGRID_SIDE_LENGTH = 3;
export const UNIQUE_SEGMENT_SUM = 45;
export const GRID_SUM = UNIQUE_SEGMENT_COUNT * UNIQUE_SEGMENT_SUM;
export const GRID_CELL_COUNT = UNIQUE_SEGMENT_COUNT * UNIQUE_SEGMENT_LENGTH;
